### ISSUE TITLE
More customization fields

### ISSUE THREAD

**Issue by bogdan-baerov** [izzy/stream-chat#36]
As discussed in https://github.com/izzy/stream-chat/issues/35, I'll put here what I think should be upgraded:
1. First of all, better differentiation between the standard vertical chat and others (the standard horizontal chat, bubble vertical, and bubble horizontal), because I have a slight issue, whenever I try to override the username color so the color for all usernames is the same in my vertical chat, even if I have two different links with different parameters(one for the vertical chat and one for the bubble vertical chat), I can't change it in any way (the "text_color" doesn't work), the only way for me to do it is in CSS and if I do that in the code, it will change my bubble username color as well since I modified the CSS part and I know it's not ok to do it like that, I tried even with "!important" and it changes the username color for every chat I'll make, another option is to just have two chat folders, one for my vertical chat, and one for the bubble chat, but that will be counter-productive, right?; **So, in short, I'd love a better differentiation between each chat format**;
2. More customization options for the bubble chat:
    - customizable border size, border radius, color (for example I use it without the border and with no rounder corners), maybe even a shadow field;
    - username font name & color.
3. Customizable announcement & highlight text options:
    - in my case, I'd want to have a specific announcement background color, message color & username color for all announcements, the same for the highlighted messages, and for now, that is not possible;
4. Maybe customizable icons (Subscriber, Bit Cheerer, Broadcaster, Moderator, VIP, Announcement, etc.).

For now, I'll keep the highlight & announcements off, and if the text_color (which affects the username from what I understand) will work for each individual link (for different chats), then the no. 1 issue for me will be solved, in my opinion, that's the biggest issue I encountered.

**Comment by izzy** [comment]
1. I'm not sure I'm understanding this right. Do you mean it's just happening in non-bubble vertical chat? Could you provide screenshots with what is happening vs. what you'd expect to see and maybe a settings URI for which it doesn't work?
2. and 3 I'll look into that rn
  * [ ] Border Size
  * [ ] Border Radius
  * [ ] Border Colour
  * [ ] Announcement Colour
  * [ ] Highlight Colour
4. Might be a bit trickier because the chat is self-contained and doesn't assume any sort of storage plus. So this is probably more of a Custom CSS/JS kinda deal. I'll think about it but right now I don't have a good solution at hand that works well for everyone :/

Also just saw your dono, thank you so much for that! :)

**Comment by izzy** [comment]
Just merged #41 so I'll close this.
